# Generated by Django 6.1.1 on 2026-10-01 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(choices=[('MDO', 'Mandal Development Officer'), ('MRO', 'Mandal Revenue Officer'), ('MUNICIPAL', 'Municipal Officer'), ('POLLUTION_BOARD', 'Pollution Control Board Officer'), ('OTHER', 'Other Designated Authority')], max_length=20)),
                ('department', models.CharField(max_length=150)),
                ('jurisdiction_area', models.CharField(help_text='e.g. a ward, mandal, or district name', max_length=150)),
                ('official_email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='officer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
